CREATE TABLE [dbo].[DailyActivity_Status](
	[kode_status] [varchar](50) NOT NULL,
	[nama_status] [varchar](150) NULL,
 CONSTRAINT [PK_DayActivity_Status] PRIMARY KEY CLUSTERED 
(
	[kode_status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

